// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
    public partial class MassRequest : IParsable
#pragma warning restore CS1591
    {
        /// <summary>The from property</summary>
        public int? From { get; set; }
        /// <summary>The to property</summary>
        public int? To { get; set; }
        /// <summary>The value property</summary>
        public double? Value { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Models.MassRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Models.MassRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Models.MassRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "from", n => { From = n.GetIntValue(); } },
                { "to", n => { To = n.GetIntValue(); } },
                { "value", n => { Value = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("from", From);
            writer.WriteIntValue("to", To);
            writer.WriteDoubleValue("value", Value);
        }
    }
}
#pragma warning restore CS0618
