// <auto-generated/>
#pragma warning disable CS0618
using CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.Length
{
        /// <summary>
        /// Builds and executes requests for operations under \api\UnitConversion\Length
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LengthRequestBuilder : BaseRequestBuilder
        {
                /// <summary>
                /// Instantiates a new <see cref="global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.Length.LengthRequestBuilder"/> and sets the default values.
                /// </summary>
                /// <param name="pathParameters">Path parameters for the request</param>
                /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
                public LengthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/UnitConversion/Length", pathParameters)
                {
                }
                /// <summary>
                /// Instantiates a new <see cref="global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.Length.LengthRequestBuilder"/> and sets the default values.
                /// </summary>
                /// <param name="rawUrl">The raw URL to use for the request builder.</param>
                /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
                public LengthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/UnitConversion/Length", rawUrl)
                {
                }
                /// <returns>A <see cref="global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Models.UnitConversionResponse"/></returns>
                /// <param name="body">The request body</param>
                /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
                /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
                public async Task<global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Models.UnitConversionResponse?> PostAsync(global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Models.LengthRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
                {
#nullable restore
#else
        public async Task<global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Models.UnitConversionResponse> PostAsync(global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Models.LengthRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
                        if (ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
                        var requestInfo = ToPostRequestInformation(body, requestConfiguration);
                        return await RequestAdapter.SendAsync<global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Models.UnitConversionResponse>(requestInfo, global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Models.UnitConversionResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
                }
                /// <returns>A <see cref="RequestInformation"/></returns>
                /// <param name="body">The request body</param>
                /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
                public RequestInformation ToPostRequestInformation(global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Models.LengthRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
                {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Models.LengthRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
                        if (ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
                        var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
                        requestInfo.Configure(requestConfiguration);
                        requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
                        requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
                        return requestInfo;
                }
                /// <summary>
                /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
                /// </summary>
                /// <returns>A <see cref="global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.Length.LengthRequestBuilder"/></returns>
                /// <param name="rawUrl">The raw URL to use for the request builder.</param>
                public global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.Length.LengthRequestBuilder WithUrl(string rawUrl)
                {
                        return new global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.Length.LengthRequestBuilder(rawUrl, RequestAdapter);
                }
                /// <summary>
                /// Configuration for the request such as headers, query parameters, and middleware options.
                /// </summary>
                [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
                [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
                public partial class LengthRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
                {
                }
        }
}
#pragma warning restore CS0618
