// <auto-generated/>
#pragma warning disable CS0618
using CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.Auth;
using CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Auth property</summary>
        public global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.Auth.AuthRequestBuilder Auth
        {
            get => new global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UnitConversion property</summary>
        public global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.UnitConversionRequestBuilder UnitConversion
        {
            get => new global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.UnitConversionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CLIESC_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
