// <auto-generated/>
#pragma warning disable CS0618
using CLICON_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.Length;
using CLICON_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.Mass;
using CLICON_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.Temperature;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CLICON_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion
{
    /// <summary>
    /// Builds and executes requests for operations under \api\UnitConversion
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UnitConversionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Length property</summary>
        public global::CLICON_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.Length.LengthRequestBuilder Length
        {
            get => new global::CLICON_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.Length.LengthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Mass property</summary>
        public global::CLICON_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.Mass.MassRequestBuilder Mass
        {
            get => new global::CLICON_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.Mass.MassRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Temperature property</summary>
        public global::CLICON_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.Temperature.TemperatureRequestBuilder Temperature
        {
            get => new global::CLICON_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.Temperature.TemperatureRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CLICON_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.UnitConversionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnitConversionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/UnitConversion", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CLICON_CONVUNI_RESTFUL_DOTNET_GR01.WebClients.Api.UnitConversion.UnitConversionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnitConversionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/UnitConversion", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
